# Generated by Django 4.0.6 on 2022-08-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillaMallMobilePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Image')),
                ('Link', models.CharField(max_length=300, verbose_name='Link')),
                ('product_name', models.CharField(max_length=500, verbose_name='Product_Name')),
                ('price', models.IntegerField(verbose_name='Price')),
            ],
        ),
    ]
