# Generated by Django 4.0.6 on 2022-08-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_shopitmobilephonemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumiafasionmodel',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='jumiamobilephonemodel',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='killamallfasionmodel',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='killamallmobilephone',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='shopitmobilephonemodel',
            name='price',
            field=models.CharField(max_length=500, verbose_name='Price'),
        ),
    ]
