# Generated by Django 4.0.6 on 2022-08-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_jumiafasionmodel_price_and_more'),
        ('base', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.shopitmobilephonemodel'),
        ),
    ]
